sudo: false
language: erlang
dist: trusty
sudo: false
otp_release:
  - 20.0
  - 19.3
  - 18.3
install:
  - ./rebar3 escriptize
script:
  - ./_build/default/bin/lasp_bench examples/null_test.config
  - ./_build/default/bin/lasp_bench examples/simple_test.config
  - ./_build/default/bin/lasp_bench examples/ets.config
